### ISSUE TITLE
Изменение языка при закрытии окна

### ISSUE THREAD

**Issue by Stakhmich** [Epsil0neR/WPF-Localization#1]
Добрый день.
Загрузил Ваш проект, но не вызывается метод LoadCompleted="Application_LoadCompleted". Поэтому язык при загрузке всегда один и тот же. Можете помочь разобраться?

**Comment by Epsil0neR** [comment]
Добрый день. Недавно проверял и действительно данный эвент по какой то причине не вызывается, тут думаю нужно искать обходные пути - напр. после инициализации первого окна. На выходных займусь этим багом и если починю, то напишу вам.

**Comment by Epsil0neR** [comment]
Починил код, посмотрите изменения в коде. Проверил VB.NET и C#
